POST http://localhost:3000/profile/v1/retrievePasswordResetToken
content-type: application/json

{
   "username": "Fabo",
   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZhYm8iLCJpYXQiOjE2NzU5NjE0OTgsImV4cCI6MTY3NjA0Nzg5OH0.DYjVBE3Mb4NLO3mGLPmAxngAp02-U0kNRATifLNWUvw"
}