version: '3.6'

services:
   
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER_DEV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DEV}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env


     