create table
  public.contacts (
    id bigint generated by default as identity,
    username text null,
    name text null,
    phone text null,
    email text null,
    constraint contacts_pkey primary key (id)
  ) tablespace pg_default;