name: Build Linky-Cloud

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
      
    - name: Get package version
      id: version
      run: echo ::set-output name=version::$(node -pe "require('./package.json').version") 

    - name: Create Tag
      run: |
        git config --global user.email "linky-cloud@proton.me"
        git config --global user.name "Fabo011"
        git tag -a v${{ steps.version.outputs.version }} -m "v${{ steps.version.outputs.version }}"

    - name: Push Tag
      run: |
        git config --global user.email "linky-cloud@proton.me"
        git config --global user.name "Fabo011"
        git push origin --tags

    - name: Build Docker image
      run: |
        docker build -t fabo011/linky-cloud:v${{ steps.version.outputs.version }} .
        docker login -u fabo011 -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push fabo011/linky-cloud:v${{ steps.version.outputs.version }}
      env:
        DOCKER_BUILDKIT: 1
