name: Build Linky-Cloud

on:
  push:
    branches: [ "pipeline" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - name: Get package version
        id: version
        run: echo ::set-output name=version::$(node -pe "require('./package.json').version") 

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PIPE_TOKEN }}

      - name: Build and Push Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          VERSION=${{ steps.version.outputs.version }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_ID:$VERSION -t $IMAGE_ID:latest .
          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:latest
