name: Build Linky-Cloud

on:
  push:
    branches: [ "v3.1.0" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
      
    - name: Switch to 'production' branch and push dist
      run: |
        git checkout -b production
        git add dist
        git commit -m "New version"
        git push origin production

